version: 2

builds:
- id: 
  binary: webhook
  main: .
  env:
  - GO_PKG=github.com/exoscale/cert-manager-webhook-exoscale
  - CGO_ENABLED=0
  flags:
  - -trimpath
  ldflags:
  - -s -w -extldflags "-static" -X main.Version={{.Version}}
  goos:
  - linux
  goarch:
  - amd64

dockers:
- goos: linux
  goarch: amd64
  image_templates:
  - "exoscale/cert-manager-webhook-exoscale:latest"
  - "exoscale/cert-manager-webhook-exoscale:{{ .Major }}"
  - "exoscale/cert-manager-webhook-exoscale:{{ .Major }}.{{ .Minor }}"
  - "exoscale/cert-manager-webhook-exoscale:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
  dockerfile: Dockerfile.goreleaser
  build_flag_templates:
  - --pull
  - --build-arg="VERSION={{.Version}}"
  - --build-arg="VCS_REF={{.ShortCommit}}"
  - --build-arg="BUILD_DATE={{.Date}}"

signs:
- cmd: gpg
  args: ["--default-key", "7100E8BFD6199CE0374CB7F003686F8CDE378D41", "--detach-sign", "${artifact}"]
  artifacts: all

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-snapshot"

release:
  github:
    owner: exoscale
    name: cert-manager-webhook-exoscale
