---
# Source: exoscale-webhook/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-webhook-exoscale
  namespace: "cert-manager"
  labels:
    app: exoscale-webhook
    chart: exoscale-webhook-0.1.0
    release: exoscale-webhook
    heritage: Helm
---
# Source: exoscale-webhook/templates/rbac.yaml
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-webhook-exoscale:domain-solver
  labels:
    app: exoscale-webhook
    chart: exoscale-webhook-0.1.0
    release: exoscale-webhook
    heritage: Helm
rules:
  - apiGroups:
      - acme.exoscale.com
    resources:
      - '*'
    verbs:
      - 'create'
---
# Source: exoscale-webhook/templates/rbac.yaml
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-exoscale:auth-delegator
  labels:
    app: exoscale-webhook
    chart: exoscale-webhook-0.1.0
    release: exoscale-webhook
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-exoscale
    namespace: cert-manager
---
# Source: exoscale-webhook/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-exoscale:domain-solver
  labels:
    app: exoscale-webhook
    chart: exoscale-webhook-0.1.0
    release: exoscale-webhook
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook-exoscale:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
---
# Source: exoscale-webhook/templates/rbac.yaml
# Grant the webhook permission to read the secrets containing the credentials
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-webhook-exoscale:secrets-reader
  namespace: cert-manager
  labels:
    app: exoscale-webhook
    chart: exoscale-webhook-0.1.0
    release: exoscale-webhook
    heritage: Helm
rules:
  - apiGroups:
    - ''
    resources:
    - 'secrets'
    verbs:
    - 'get'
---
# Source: exoscale-webhook/templates/rbac.yaml
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-exoscale:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: exoscale-webhook
    chart: exoscale-webhook-0.1.0
    release: exoscale-webhook
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-exoscale
    namespace: cert-manager
---
# Source: exoscale-webhook/templates/rbac.yaml
# Grant the webhook permission to read the secrets containing the credentials
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-exoscale:secrets-reader
  namespace: cert-manager
  labels:
    app: exoscale-webhook
    chart: exoscale-webhook-0.1.0
    release: exoscale-webhook
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-webhook-exoscale:secrets-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-exoscale
    namespace: cert-manager
---
# Source: exoscale-webhook/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook-exoscale
  namespace: "cert-manager"
  labels:
    app: exoscale-webhook
    chart: exoscale-webhook-0.1.0
    release: exoscale-webhook
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: exoscale-webhook
    release: exoscale-webhook
---
# Source: exoscale-webhook/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook-exoscale
  namespace: "cert-manager"
  labels:
    app: exoscale-webhook
    chart: exoscale-webhook-0.1.0
    release: exoscale-webhook
    heritage: Helm
spec:
  replicas: 
  selector:
    matchLabels:
      app: exoscale-webhook
      release: exoscale-webhook
  template:
    metadata:
      labels:
        app: exoscale-webhook
        release: exoscale-webhook
    spec:
      serviceAccountName: cert-manager-webhook-exoscale
      containers:
        - name: exoscale-webhook
          image: "exoscale/cert-manager-webhook-exoscale:dev"
          imagePullPolicy: IfNotPresent
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            - name: GROUP_NAME
              value: "acme.exoscale.com"
            - name: EXOSCALE_DEBUG
              value: ""
            - name: EXOSCALE_API_TRACE
              value: ""
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          resources:
            {}
      volumes:
        - name: certs
          secret:
            secretName: cert-manager-webhook-exoscale-webhook-tls
---
# Source: exoscale-webhook/templates/apiservice.yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.acme.exoscale.com
  labels:
    app: exoscale-webhook
    chart: exoscale-webhook-0.1.0
    release: exoscale-webhook
    heritage: Helm
  annotations:
    cert-manager.io/inject-ca-from: "cert-manager/cert-manager-webhook-exoscale-webhook-tls"
spec:
  group: acme.exoscale.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: cert-manager-webhook-exoscale
    namespace: cert-manager
  version: v1alpha1
---
# Source: exoscale-webhook/templates/pki.yaml
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-exoscale-ca
  namespace: "cert-manager"
  labels:
    app: exoscale-webhook
    chart: exoscale-webhook-0.1.0
    release: exoscale-webhook
    heritage: Helm
spec:
  secretName: cert-manager-webhook-exoscale-ca
  duration: 43800h # 5y
  issuerRef:
    name: cert-manager-webhook-exoscale-selfsign
  commonName: "ca.exoscale-webhook.cert-manager"
  isCA: true
---
# Source: exoscale-webhook/templates/pki.yaml
# Finally, generate a serving certificate for the webhook to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-exoscale-webhook-tls
  namespace: "cert-manager"
  labels:
    app: exoscale-webhook
    chart: exoscale-webhook-0.1.0
    release: exoscale-webhook
    heritage: Helm
spec:
  secretName: cert-manager-webhook-exoscale-webhook-tls
  duration: 8760h # 1y
  issuerRef:
    name: cert-manager-webhook-exoscale-ca
  dnsNames:
  - cert-manager-webhook-exoscale
  - cert-manager-webhook-exoscale.cert-manager
  - cert-manager-webhook-exoscale.cert-manager.svc
---
# Source: exoscale-webhook/templates/pki.yaml
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-webhook-exoscale-selfsign
  namespace: "cert-manager"
  labels:
    app: exoscale-webhook
    chart: exoscale-webhook-0.1.0
    release: exoscale-webhook
    heritage: Helm
spec:
  selfSigned: {}
---
# Source: exoscale-webhook/templates/pki.yaml
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-webhook-exoscale-ca
  namespace: "cert-manager"
  labels:
    app: exoscale-webhook
    chart: exoscale-webhook-0.1.0
    release: exoscale-webhook
    heritage: Helm
spec:
  ca:
    secretName: cert-manager-webhook-exoscale-ca
