name: CI

on:
  push:
    branches:
    - '**'
    paths-ignore:
    - '**.md'
    tags-ignore:
    - 'v*' # Don't run workflow on release tags

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.18'
    - name: Lint code
      run: |
        make go.mk
        PATH=$(go env GOPATH)/bin:$PATH make lint
